fix args
:+1: Fixed arguments not working

diff --git a/susie b/susie
--- a/susie
+++ b/susie
@@ -1,1 +1,1 @@
-echo "$(zenity --title "SUsie by Sparksammy" --password)" | sudo -S -k $1 || echo "Task ended due to possible error. Error code: $?." 
+echo "$(zenity --title "SUsie by Sparksammy" --password)" | sudo -S -k $@ || echo "Task ended due to possible error. Error code: $?." 
